import { atom } from 'recoil';

export const B01001010_store = atom({
  key: 'B01001010',
  default: {
    p01: {
      answer: '',
      solution: '',
      isCorrect: false,
      isSubmitted: false,
    },
    p02: {
      answer1: '',
      answer2: '',
      solution1: '416',
      solution2: '135',
      isCorrect: false,
      isSubmitted: false,
    },
    p03: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      answer5: '',
      answer6: '',
      solution1: '416',
      solution2: '135',
      solution3_and_solution4: '416+135=551',
      solution5: '551',
      solution6: '551',
      isCorrect: false,
      isSubmitted: false,
    },
    p04: {
      answer1: '',
      answer2: '',
      solution1: '287',
      solution2: '121',
      isCorrect: false,
      isSubmitted: false,
    },
    p05: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      answer5: '',
      answer6: '',
      solution1: '287',
      solution2: '121',
      solution3: '287',
      solution4: '121',
      solution5: '166',
      solution6: '166',
      isCorrect: false,
      isSubmitted: false,
    },
  },
});
