import { atom } from 'recoil';
export const B01001140 = atom({
  key: 'B01001140',
  default: {
    P01: {
      index: 1,
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '4',
      solution2: '7',
      solution3: '5',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    P02: {
      index: 2,
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '1',
      solution2: '9',
      solution3: '6',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    P03: {
      index: 3,
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '0',
      solution2: '2',
      solution3: '4',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    P04: {
      index: 4,
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '4',
      solution2: '1',
      solution3: '4',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    P05: {
      index: 5,
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '5',
      solution2: '2',
      solution3: '3',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    p06: {
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '4',
      solution2: '7',
      solution3: '8',
      isCorrect: false,
      isSubmitted: false,
    },
    p07: {
      answer1: '',
      solution1:'1003',
      isCorrect: false,
      isSubmitted: false,
    },
    p08: {
      answer1: '',
      solution1:'689',
      isCorrect: false,
      isSubmitted: false,
    },
    p09: {
      answer1: '',
      solution1:'449',
      isCorrect: false,
      isSubmitted: false,
    },
    p10: {
      answer1: '',
      solution1:'261',
      isCorrect: false,
      isSubmitted: false,
    },
  },
});


