import { atom } from 'recoil';

export const A01_0011_04 = atom({
  key: 'A01_0011_04',
  default: {
    p01: {
      answer1: [-1, -1, -1],
      answer2: [-1, -1, -1],
      answer3: -1,
      answer4: -1,
      solution1: [7, 9, 4],
      solution2: [7, 4, 6],
      solution3: 497,
      solution4: 296,
      isCorrect: false,
      isSubmitted: false,
    },
    p02: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      solution1: 'biggerLeft',
      solution2: 'biggerRight',
      solution3: 'equal',
      solution4: 'biggerLeft',
      isCorrect: false,
      isSubmitted: false,
    },
    p03: {
      answer1: '',
      answer2: '',
      solution1: '982',
      solution2: '689',
      isCorrect: false,
      isSubmitted: false,
    },
    p04: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      answer5: '',
      solution1: '7',
      solution2: '7',
      solution3: '7',
      solution4: '17',
      solution5: '1',
      isCorrect: false,
      isSubmitted: false,
    },
    p05: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      answerRadio: 0,
      solution1: '800',
      solution2: '500',
      solution3: '1300',
      solution4: '1300',
      solutionRadio: 2,
      isCorrect: false,
      isSubmitted: false,
    },
    p06: {
      answer1: '',
      answer2: '',
      solution1: ['813+489=1302', '489+813=1302', '489+813', '813+489'],
      solution2: '1302',
      isCorrect: false,
      isSubmitted: false,
    },
    p07: {
      answer: '',
      solution: '1',
      isCorrect: false,
      isSubmitted: false,
    },
  },
});
