import { atom } from 'recoil';

export const C01000810_Atom = atom({
  key: 'C01000810',
  default: {
    p02: {
      answer1: {
        value: '',
        isCorrect: false,
      },
      answer2: {
        value: '',
        isCorrect: false,
      },
      answer3: {
        value: '',
        isCorrect: false,
      },
      answer4: {
        value: '',
        isCorrect: false,
      },
      answer5: {
        value: '',
        isCorrect: false,
      },
      solution1: '500',
      solution2: '500',
      solution3: '500',
      solution4: '500',
      solution5: '1000',
      isSubmitted: false,
      isCorrect: false,
    },
    p03: {
      answer1: {
        value: '',
        isCorrect: false,
      },
      answer2: {
        value: '',
        isCorrect: false,
      },
      isSubmitted: false,
      isCorrect: false,
    },
    p04: {
      answer1: {
        value: '',
        isCorrect: false,
      },
      answer2: {
        value: '',
        isCorrect: false,
      },
      answer3: {
        value: '',
        isCorrect: false,
      },
      answer4: {
        value: '',
        isCorrect: false,
      },
      answer5: {
        value: '',
        isCorrect: false,
      },
      solution1: '496',
      solution2: '508',
      solution3: '1004',
      solution4: '1004',
      solution5: '1',
      isSubmitted: false,
      isCorrect: false,
    },
    p06: {
      answer: '',
      solution: '399',
      isCorrect: false,
      isSubmitted: false,
    },
    p07: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      solution1: '400',
      solution2: '800',
      solution3: '400',
      solution4: '400',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isCorrect4: false,
      isSubmitted: false,
    },
    p08: {
      answer1: 0,
      answer2: '',
      answer3: '',
      solution1: 1,
      solution2: '400',
      solution3: '399',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    p09: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      answer5: 0,
      solution1: '800',
      solution2: '389',
      solution3: '411',
      solution4: '411',
      solution5: 1,
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isCorrect4: false,
      isCorrect5: false,
      isSubmitted: false,
    },
  },
});
