import { layouts } from '@/constants/layout';
import { lazyLoad } from '@maidt-cntn/router';
import { ELayout } from '@maidt-cntn/ui';
import { RouteObject } from 'react-router-dom';
import { IMMLayoutDataTypes } from '../../App';

export declare type IMMRouteObject = Omit<RouteObject, 'children'> & {
  params?: IMMLayoutDataTypes;
  children?: IMMRouteObject[];
};

const router: IMMRouteObject[] = [
  {
    path: '',
    element: lazyLoad(() => import('../../App')),
    children: [
      {
        path: `A010100-06`,
        element: lazyLoad(() => import('../../cards/A01/0100/06')),
        params: {
          ...layouts[ELayout.INTRO],
        },
        children: [],
      },

      {
        path: `A010000-01`,
        element: lazyLoad(() => import('../../cards/A01/0000/01')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
        },
        children: [],
      },
      {
        path: `A010000-02`,
        element: lazyLoad(() => import('../../cards/A01/0000/02')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
        },
        children: [],
      },
      {
        path: `A010000-03`,
        element: lazyLoad(() => import('../../cards/A01/0000/03')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
        },
        children: [],
      },
      {
        path: `A010000-04`,
        element: lazyLoad(() => import('../../cards/A01/0000/04')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
        },
        children: [],
      },
      {
        path: 'A010002-06',
        element: lazyLoad(() => import('../../cards/A01/0002/06')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: `A010003-16`,
        element: lazyLoad(() => import('../../cards/A01/0003/16')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010002-15`,
        element: lazyLoad(() => import('../../cards/A01/0002/15')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
        children: [],
      },
      {
        path: 'A010002-07',
        element: lazyLoad(() => import('../../cards/A01/0002/07')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: `A010000-05`,
        element: lazyLoad(() => import('../../cards/A01/0000/05')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: '#FECD6A',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
          footerBackColor: '#FECD6A',
        },
        children: [],
      },
      {
        path: `A010000-06`,
        element: lazyLoad(() => import('../../cards/A01/0000/06')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
        },
        children: [],
      },

      {
        path: `A010001-01`,
        element: lazyLoad(() => import('../../cards/A01/0001/01')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-02`,
        element: lazyLoad(() => import('../../cards/A01/0001/02')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-03`,
        element: lazyLoad(() => import('../../cards/A01/0001/03')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-04`,
        element: lazyLoad(() => import('../../cards/A01/0001/04')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-05`,
        element: lazyLoad(() => import('../../cards/A01/0001/05')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-06`,
        element: lazyLoad(() => import('../../cards/A01/0001/06')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-07`,
        element: lazyLoad(() => import('../../cards/A01/0001/07')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'beige',
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-08`,
        element: lazyLoad(() => import('../../cards/A01/0001/08')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'green',
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-09`,
        element: lazyLoad(() => import('../../cards/A01/0001/09')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '1. 소수와 합성수',
        },
      },
      {
        path: `A010001-10`,
        element: lazyLoad(() => import('../../cards/A01/0001/10')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'blue',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '1. 소수와 합성수',
        },
      },
      {
        path: `A010001-11`,
        element: lazyLoad(() => import('../../cards/A01/0001/11')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010001-12`,
        element: lazyLoad(() => import('../../cards/A01/0001/12')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },

      {
        path: `A010002-01`,
        element: lazyLoad(() => import('../../cards/A01/0002/01')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
      },
      {
        path: `A010002-02`,
        element: lazyLoad(() => import('../../cards/A01/0002/02')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
      },
      {
        path: 'A010002-03',
        element: lazyLoad(() => import('../../cards/A01/0002/03')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: 'A010002-04',
        element: lazyLoad(() => import('../../cards/A01/0002/04')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
      },
      {
        path: 'A010002-05',
        element: lazyLoad(() => import('../../cards/A01/0002/05')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: 'A010002-06',
        element: lazyLoad(() => import('../../cards/A01/0002/06')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '1. 소수와 합성수',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: 'A010002-07',
        element: lazyLoad(() => import('../../cards/A01/0002/07')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: `A010002-08`,
        element: lazyLoad(() => import('../../cards/A01/0002/08')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
        children: [],
      },
      {
        path: `A010002-09`,
        element: lazyLoad(() => import('../../cards/A01/0002/09')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
        children: [],
      },
      {
        path: 'A010002-10',
        element: lazyLoad(() => import('../../cards/A01/0002/10')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: 'A010002-11',
        element: lazyLoad(() => import('../../cards/A01/0002/11')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: 'A010002-12',
        element: lazyLoad(() => import('../../cards/A01/0002/12')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: 'A010002-13',
        element: lazyLoad(() => import('../../cards/A01/0002/13')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: 'A010002-14',
        element: lazyLoad(() => import('../../cards/A01/0002/14')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: `A010002-15`,
        element: lazyLoad(() => import('../../cards/A01/0002/15')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
        children: [],
      },
      {
        path: `A010002-16`,
        element: lazyLoad(() => import('../../cards/A01/0002/16')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소수와 합성수',
        },
        children: [],
      },
      {
        path: `A010002-17`,
        element: lazyLoad(() => import('../../cards/A01/0002/17')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
        children: [],
      },
      {
        path: `A010002-18`,
        element: lazyLoad(() => import('../../cards/A01/0002/18')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '2. 소인수분해',
        },
        children: [],
      },

      {
        path: `A010003-01`,
        element: lazyLoad(() => import('../../cards/A01/0003/01')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-02`,
        element: lazyLoad(() => import('../../cards/A01/0003/02')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-03`,
        element: lazyLoad(() => import('../../cards/A01/0003/03')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-04`,
        element: lazyLoad(() => import('../../cards/A01/0003/04')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-05`,
        element: lazyLoad(() => import('../../cards/A01/0003/05')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-06`,
        element: lazyLoad(() => import('../../cards/A01/0003/06')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-07`,
        element: lazyLoad(() => import('../../cards/A01/0003/07')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-08`,
        element: lazyLoad(() => import('../../cards/A01/0003/08')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-09`,
        element: lazyLoad(() => import('../../cards/A01/0003/09')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-10`,
        element: lazyLoad(() => import('../../cards/A01/0003/10')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-11`,
        element: lazyLoad(() => import('../../cards/A01/0003/11')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-12`,
        element: lazyLoad(() => import('../../cards/A01/0003/12')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-13`,
        element: lazyLoad(() => import('../../cards/A01/0003/13')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-14`,
        element: lazyLoad(() => import('../../cards/A01/0003/14')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-15`,
        element: lazyLoad(() => import('../../cards/A01/0003/15')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },
      {
        path: `A010003-16`,
        element: lazyLoad(() => import('../../cards/A01/0003/16')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '3. 최대공약수와 최소공배수',
        },
        children: [],
      },

      {
        path: `A010099-01`,
        element: lazyLoad(() => import('../../cards/A01/0099/01')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
        },
        children: [],
      },
      {
        path: `A010099-02`,
        element: lazyLoad(() => import('../../cards/A01/0099/02')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'blue',
          chapterNum: '',
          mainChapter: '1. 소인수분해',
          subChapter: '',
        },
        children: [],
      },
      {
        path: `A010099-03`,
        element: lazyLoad(() => import('../../cards/A01/0099/03')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: `A010099-04`,
        element: lazyLoad(() => import('../../cards/A01/0099/04')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '',
          backGroundColor: 'yellow',
        },
        children: [],
      },
      {
        path: `A010099-05`,
        element: lazyLoad(() => import('../../cards/A01/0099/05')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '',
          backGroundColor: 'blue',
        },
        children: [],
      },
      {
        path: `A010002-02`,
        element: lazyLoad(() => import('../../cards/A01/0002/02')),
        params: {
          ...layouts[ELayout.INTRO],
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '2. 소인수분해',
          backGroundColor: 'yellow',
        },
        children: [],
      },
    ],
  },
  {
    path: '',
    element: lazyLoad(() => import('../../App')),
    children: [
      {
        path: `A010001-10`,
        element: lazyLoad(() => import('../../cards/A01/0001/10')),
        params: {
          ...layouts[ELayout.INTRO],
          backGroundColor: 'yellow',
          chapterNum: '1.',
          mainChapter: '소인수분해',
          subChapter: '1. 소수와 합성수',
        },
        children: [],
      },
    ],
  },
];

export default router;
