import { ELayout, TLayoutDataTypes } from '@maidt-cntn/ui';

export const layouts: TLayoutDataTypes = {
  [ELayout.DEFAULT]: {
    backGroundColor: 'blue',
    chapterNum: '1.',
    mainChapter: '대단원을 입력해 주세요 대단원을 입력해 주세요',
    subChapter: '중단원을 입력해 주세요 중단원을 입력해 주세요',
    minorChapter: '소단원을 입력해 주세요 소단원을 입력해 주세요',
    headerPattern: 'number', // "text" | "icon" | "number"
    headerText: '대제목을 입력해주세요',
    headerNumber: 1,
    iconType: 'teacher',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.INTRO]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 1.',
    mainChapter: 'You and I Become “We”',
    subChapter: 'Intro',
    minorChapter: '',
    headerPattern: 'text',
    headerText: 'Warm Up',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.SECONDARY]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 1.',
    mainChapter: 'How Are you?',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.TERTIARY]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 1.',
    mainChapter: 'How Are you?',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.QUATERNARY]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 1.',
    mainChapter: 'How Are you?',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.QUINARY]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 1.',
    mainChapter: 'How Are you?',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L01SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 1.',
    mainChapter: 'How Are You?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L01SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 1.',
    mainChapter: 'How Are You?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },

  // Lesson 2
  [ELayout.L02C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L02SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 2.',
    mainChapter: 'This Is My Dad',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 3
  [ELayout.L03C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L03SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 3.',
    mainChapter: 'Who Is She?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 4
  [ELayout.L04C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 4.',
    mainChapter: 'Don’t Run, Please',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L04C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 4.',
    mainChapter: 'Don’t Run, Please',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L04C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 4.',
    mainChapter: 'Don’t Run, Please',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L04C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 4.',
    mainChapter: 'Don’t Run, Please',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L04SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 4.',
    mainChapter: 'Don’t Run, Please',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L04SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 4.',
    mainChapter: 'Don’t Run, Please',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L04SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 4.',
    mainChapter: 'Don’t Run, Please',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 5
  [ELayout.L05C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L05SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 5.',
    mainChapter: 'Let’s Play Soccer',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 6
  [ELayout.L06C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L06SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 6.',
    mainChapter: 'I’m Cooking',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 7
  [ELayout.L07C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07C02]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07C03]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L07SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 7.',
    mainChapter: 'What Time Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 8
  [ELayout.L08C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L08SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 8.',
    mainChapter: 'How Much Is It?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 9
  [ELayout.L09C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L09SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 9.',
    mainChapter: 'It’s Under The Desk',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 10
  [ELayout.L10C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L10SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 10.',
    mainChapter: 'Is This Your Shoe?',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 11
  [ELayout.L11C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L11SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 11.',
    mainChapter: 'It’s Friday',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Lesson 12
  [ELayout.L12C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12C03]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '3차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12C04]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '4차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12SP01]: {
    backGroundColor: 'pink',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12SP02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12SP03]: {
    backGroundColor: 'brown',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12SP04]: {
    backGroundColor: 'green',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.L12SP05]: {
    backGroundColor: 'blue',
    chapterNum: 'Lesson 12.',
    mainChapter: 'I Ride My Bike',
    subChapter: '보충학습',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Link 1
  [ELayout.LK1C01]: {
    backGroundColor: 'green',
    chapterNum: 'Link 1.',
    mainChapter: '',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.LK1C02]: {
    backGroundColor: 'blue',
    chapterNum: 'Link 1.',
    mainChapter: '',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Link 2
  [ELayout.LK2C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Link 2.',
    mainChapter: '',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.LK2C02]: {
    backGroundColor: 'brown',
    chapterNum: 'Link 2.',
    mainChapter: '',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Link 3
  [ELayout.LK3C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Link 3.',
    mainChapter: '',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.LK3C02]: {
    backGroundColor: 'blue',
    chapterNum: 'Link 3.',
    mainChapter: '',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // Link 4
  [ELayout.LK4C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Link 4.',
    mainChapter: '',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.LK4C02]: {
    backGroundColor: 'blue',
    chapterNum: 'Link 4.',
    mainChapter: '',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // SL1
  [ELayout.SL1C01]: {
    backGroundColor: 'pink',
    chapterNum: 'Hello, My World',
    mainChapter: '',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  [ELayout.SL1C02]: {
    backGroundColor: 'yellow',
    chapterNum: 'Hello, My World',
    mainChapter: '',
    subChapter: '2차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
  // SL2
  [ELayout.SL2C01]: {
    backGroundColor: 'blue',
    chapterNum: 'Goodbye',
    mainChapter: '',
    subChapter: '1차시',
    minorChapter: '',
    headerPattern: 'text',
    headerText: '대제목을 입력해주세요',
    footerInfo: {
      footerColorType: 'white',
    },
  },
};
