import { atom } from 'recoil';

export const A05001204_Atom = atom({
  key: 'A05001204',
  default: {
    p01: {
      answer: '',
      solution1: '',
      isCorrect: false,
      isSubmitted: false,
    },
    p02: {
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '83',
      solution2: '9',
      solution3: '7',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    p03: {
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '2050',
      solution2: '3',
      solution3: '450',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    p04: {
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '75',
      solution2: '2',
      solution3: '30',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
    p05: {
      answer1: '',
      answer2: '',
      solution: ['ㄱ','ㄹ'],
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isSubmitted: false,
    },
    p06: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      solution1: '소연',
      solution2: '9',
      solution3: '9',
      solution4: '20',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isCorrect4: false,
      isSubmitted: false,
    },
    p07: {
      answer: '',
      solution: '2500',
      isCorrect: false,
      isSubmitted: false,
    },
    p08: {
      answer1: '',
      answer2: '',
      answer3: '',
      solution1: '1',
      solution2: '45',
      solution3: '15',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isSubmitted: false,
    },
  },
});
