import { atom } from 'recoil';

export const A04000904_Atom = atom({
  key: 'A04000904',
  default: {
    p01: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      answer5: '',
      answer6: '',
      solution1: '2',
      solution2: '1',
      solution3: '0',
      solution4: '6',
      solution5: '2',
      solution6: '7',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isCorrect4: false,
      isCorrect5: false,
      isCorrect6: false,
      isSubmitted: false,
    },
    p02: {
      answer1: '',
      answer2: '',
      answer3: ['', '', ''],
      answer4: ['', '', ''],
      solution1: '60',
      solution2: '44',
      solution3: ['2', '0', '5'],
      solution4: ['1', '6', '2'],
      isCorrect: false,
      isSubmitted: false,
    },
    p03: {
      answer: 0,
      solution: 2,
      isCorrect: false,
      isSubmitted: false,
    },
    p04: {
      answer1: '',
      answer2: '',
      solution1: '26',
      solution2: '78',
      isCorrect1: false,
      isCorrect2: false,
      isCorrect: false,
      isSubmitted: false,
    },
    p05: {
      answer: '',
      solution: '태호',
      isCorrect: false,
      isSubmitted: false,
    },
    p06: {
      answer1: '',
      answer2: '',
      answer3: '',
      answer4: '',
      solution1: '3',
      solution2: '2',
      solution3: '8',
      solution4: '256',
      isCorrect: false,
      isCorrect1: false,
      isCorrect2: false,
      isCorrect3: false,
      isCorrect4: false,
      isSubmitted: false,
    },
  },
});
